"""Operational defaults shared by the campaign generator package.

Prompts, creative-angle catalogs, and synthetic brief content live with their
owning modules. Environment variables are read at runtime by entrypoints.
"""

from pathlib import Path

# Models and provenance
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
CODE_COMMIT_ENV = "CODE_COMMIT"
GCP_PROJECT_ENV = "CAMPAIGN_GCP_PROJECT"
BASE_MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
BASE_MODEL_REVISION = "989aa7980e4cf806f80c7fef2b1adb7bc71aa306"
TEACHER_MODEL_ID = "gpt-6-luna"
JUDGE_MODEL_ID = "gpt-6-astra"
PROMPT_VERSION = "brief-to-campaign-description-v2"

# Public API and private inference
API_TITLE = "Campaign Generation API"
API_VERSION = "1.0.0"
INFERENCE_URL_ENV = "INFERENCE_URL"
INFERENCE_AUDIENCE_ENV = "INFERENCE_AUDIENCE"
API_MAX_BODY_BYTES = 8 * 1024
API_TIMEOUT_SECONDS = 900
API_MAX_CHANNELS = 10
API_MAX_CONSTRAINTS = 20
API_MAX_BRIEF_TEXT_LENGTH = 1000
API_REJECTED_LOG_LENGTH = 500
API_NAME_SIMILARITY_THRESHOLD = 0.82
API_DESCRIPTION_CHANNEL_LIMIT = 3
API_DESCRIPTION_MIN_SENTENCES = 2
API_DESCRIPTION_MAX_SENTENCES = 3
API_CONCEPT_ATTEMPTS = 3
API_CONCEPT_COUNT = 3
API_MAX_OUTPUT_TOKENS = 1536
INFERENCE_TIMEOUT_SECONDS = 300.0
INFERENCE_MODEL_NAME = "campaign-baseline"
INFERENCE_TEMPERATURE = 0.2

# Dataset v3
DATASET_NAME = "baseline-v3-description-seed42"
DATASET_SEED = 42
DATASET_SYNTHETIC_BRIEF_COUNT = 120
DATASET_CANDIDATE_COUNT = 240
DATASET_TEACHER_WORKERS = 4
DATASET_PROGRESS_INTERVAL = 20
DATASET_LEGACY_SPLIT_COUNTS = {"train": 96, "validation": 12, "test": 12}
DATASET_SYNTHETIC_SPLIT_COUNTS = {"train": 72, "validation": 12, "test": 36}
DATASET_SPLIT_COUNTS = {"train": 168, "validation": 24, "test": 48}
DATASET_DEFAULT_SOURCE_BRIEFS = Path("dataset/source_briefs.jsonl")
DATASET_DEFAULT_OUTPUT_DIR = Path("data/processed/dataset-v3")
DATASET_DEFAULT_CACHE = Path("data/cache/baseline-v3-description.sqlite3")
DEFAULT_GCP_PROJECT_ID = "campaign-generator-509812"
DATASET_BUCKET_SUFFIX = "-dataset"
DATASET_FINAL_FILES = ("manifest.json", "train.jsonl", "validation.jsonl", "test.jsonl", "quality_report.md")
DATASET_DRAFT_FILES = (
    "manifest.json",
    "drafts.jsonl",
    "review_queue.jsonl",
    "review_template.jsonl",
    "synthetic_briefs.jsonl",
    "brief_manifest.json",
    "HUMAN_REVIEW.md",
)

# LoRA training
TRAIN_MAX_SEQUENCE_LENGTH = 4096
TRAIN_SEQUENCE_PERCENTILE = 0.95
TRAIN_SEQUENCE_ROUND_TO = 256
TRAIN_SMOKE_SEQUENCE_LIMIT = 1024
TRAIN_SMOKE_ROW_COUNT = 8
TRAIN_SMOKE_MAX_STEPS = 20
TRAIN_SMOKE_MICROBATCH = 1
TRAIN_SMOKE_GRADIENT_ACCUMULATION = 1
TRAIN_DEFAULT_MAX_STEPS = -1
TRAIN_LABEL_IGNORE_INDEX = -100
TRAIN_LORA_R = 16
TRAIN_LORA_ALPHA = 32
TRAIN_LORA_DROPOUT = 0.05
TRAIN_LORA_BIAS = "none"
TRAIN_LORA_TASK_TYPE = "CAUSAL_LM"
TRAIN_LORA_TARGET_MODULES = ("q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj")
TRAIN_LEARNING_RATE = 2e-4
TRAIN_EPOCHS = 3
TRAIN_MICROBATCH = 4
TRAIN_EVAL_BATCH = 4
TRAIN_GRADIENT_ACCUMULATION = 8
TRAIN_LOGGING_STEPS = 5
TRAIN_CHECKPOINT_STEPS = 25
TRAIN_CHECKPOINT_LIMIT = 2
TRAIN_EVAL_METRIC = "eval_loss"
TRAIN_SEED = 42
TRAIN_DEFAULT_WORK_DIR = Path("/tmp/campaign-training")

# Offline evaluation and promotion
EVAL_HOLDOUT_COUNT = 36
EVAL_LIVE_LIMIT = 20
EVAL_LIVE_TIMEOUT_SECONDS = 900.0
EVAL_LIVE_BUDGET_MIN = 100000
EVAL_LIVE_BUDGET_MAX = 300000
EVAL_LIVE_BUDGET_CURRENCY = "THB"
EVAL_JUDGE_EXPECTED_IDEAS = 10
EVAL_JUDGE_MODE = "ideas"
EVAL_JUDGE_LIMIT = 30
EVAL_BOOTSTRAP_SEED = 42
EVAL_BOOTSTRAP_SAMPLES = 10_000
EVAL_DIAGNOSTIC_PER_SOURCE = 6
EVAL_LORA_PER_SOURCE = 3
EVAL_LORA_MAX_ATTEMPTS = 6
EVAL_LORA_TEMPERATURE = 0.7
EVAL_LORA_TOP_P = 0.9
PROMOTION_MIN_NET_WIN_POINTS = 10
PROMOTION_MIN_FORMAT_PASS_RATE = 0.98
PROMOTION_MAX_RUBRIC_REGRESSION_POINTS = 2
